### ISSUE TITLE
tech02/BackStackSampleにプロジェクトが入っていないです

### ISSUE THREAD

**Issue by kanjihtmt** [advanced-android-book/samples#2]
書籍を購入し、サンプルをgithubで確認しましたが.ideaしか入っていないようです。
ご確認頂けないでしょうか？

**Comment by luckpoint** [comment]
ご連絡ありがとうございます！
こちら確認しました。修正いたします。

**Comment by luckpoint** [comment]
こちら不要なファイルだったため、先ほど削除しました。
