### ISSUE TITLE
ContentResolver#queryメソッドはnullを返すかもしれないのでnullチェックを含めた方がいい

### ISSUE THREAD

**Issue by operando** [advanced-android-book/samples#5]
ContentResolver#queryメソッドはnullを返すかもしれないのでnullチェックを含めた方がいい。

公式のドキュメントの戻り値にも以下の記載があります。

```
A Cursor object, which is positioned before the first entry, or null
```

ただ、今回のsampleで使用しているものではnullが返ることは確認されていません。

あくまでドキュメントに上記のような記載があるので、nullチェックをした方がよいのではないかというご提案です。
## サンプル名
- ContentProviderSample
- https://github.com/advanced-android-book/samples/tree/master/tech03/ContentProviderSample
### 該当のサンプルコード
- https://github.com/advanced-android-book/samples/blob/master/tech03/ContentProviderSample/app/src/main/java/com/advanced_android/contentprovidersample/MainActivity.java#L28-L29
## ContentResolver#queryメソッドのドキュメント

https://developer.android.com/reference/android/content/ContentResolver.html#query(android.net.Uri, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String, android.os.CancellationSignal)

**Comment by luckpoint** [comment]
ご提案ありがとうございます！
こちら修正を行います。

なお、README.mdにも記載を行いましたが、修正はsupportブランチにて行います。
（書籍の都合上、masterには反映されないことご了承ください）
