### ISSUE TITLE
tech02/FragmentTransactionSamleの起動時にクラッシュ

### ISSUE THREAD

**Issue by Ogiwara-CostlierRain464** [advanced-android-book/samples#8]
## サンプル名
tech02/FragmentTransactionSamle

## Androidのバージョン・機種名
7.0.0, LG V20pro

## 再現手順
起動時にクラッシュ

## 発生頻度 (3回に1回発生、毎回発生など)
毎回発生

## 期待される動作
クラッシュしないこと

## Logcatの出力 (もし可能なら)
MainActivityのmListenerを初期化代入するコードの内の、
fragmentManager.fragmentsでNullPointerException

**Comment by Ogiwara-CostlierRain464** [comment]
Nullチェックによる問題の応急処置

**Comment by luckpoint** [comment]
（GWの休暇中で返信おそくなりました。)

不具合のレポートありがとうございます。nullチェックを追加しました。
